import type { FormFieldGroupType, UsableFormFieldGroup } from "../types";

export const usableFieldsList: UsableFormFieldGroup[] = [
  {
    id: 'applicationInfo',
    title: '지원정보',
    collapse: false,
    selected: false,
    items: {
      jobPosition: { field: { type: 'text', label: '지원 직무' }, use: false },
      preferredLocation: { field: { type: 'text', label: '희망 근무지' }, use: false },
      applicationSource: { field: { type: 'text', label: '지원 경로' }, use: false },
      desiredSalary: { field: { type: 'text', label: '희망 연봉' }, use: false },
      previousSalary: { field: { type: 'text', label: '직전 연봉' }, use: false },
      availableStartDate: { field: { type: 'text', label: '입사가능일자' }, use: false },
      previousPosition: { field: { type: 'text', label: '직전직급' }, use: false },
      applicationPath: { field: { type: 'text', label: '지원경로' }, use: false },
    },
    sort: 0,
  },          
  {
    id: 'personalInfo',
    title: '인적정보',
    collapse: false,
    selected: false,
    items: {
      photo: { field: { type: 'text', label: '사진' }, use: false },
      name: { field: { type: 'text', label: '이름' }, use: false },
      englishName: { field: { type: 'text', label: '영문 이름' }, use: false },
      phoneNumber: { field: { type: 'text', label: '휴대폰 번호' }, use: false },
      email: { field: { type: 'text', label: '이메일' }, use: false },
      emergencyContact: { field: { type: 'text', label: '긴급 연락처' }, use: false },
      birthDate: { field: { type: 'text', label: '생년월일' }, use: false },
      gender: { field: { type: 'text', label: '성별' }, use: false },
      hobby: { field: { type: 'text', label: '취미' }, use: false },
      specialty: { field: { type: 'text', label: '특기' }, use: false },
      colorVision: { field: { type: 'text', label: '색약여부' }, use: false },
      militaryService: { field: { type: 'text', label: '병역' }, use: false },
      address: { field: { type: 'text', label: '주소' }, use: false },
      snsUrl: { field: { type: 'text', label: 'SNS주소' }, use: false },
      nationality: { field: { type: 'text', label: '국적' }, use: false },
    },
    sort: 0,
  },           
  {
    id: 'summaryInfo',
    title: '요약정보',
    collapse: false,
    selected: false,
    items: {

    },
    sort: 0,
  },              
  {
    id: 'additionalPoints',
    title: '가산점',
    collapse: false,
    selected: false,
    items: {
      disability: { field: { type: 'text', label: '장애 여부' }, use: false },
      veteransStatus: { field: { type: 'text', label: '보훈 대상 여부' }, use: false },
      localTalent: { field: { type: 'text', label: '지역 인재' }, use: false },
      formerLocalTalent: { field: { type: 'text', label: '이전 지역 인재' }, use: false },
      singleParent: { field: { type: 'text', label: '한부모 가족 여부' }, use: false },
      northKoreanDefector: { field: { type: 'text', label: '북한 이탈 주민 여부' }, use: false },
      basicLivingRecipient: { field: { type: 'text', label: '기초생활 수급 여부' }, use: false },
      lowIncome: { field: { type: 'text', label: '차상위계층여부' }, use: false },
      youth: { field: { type: 'text', label: '청년 여부' }, use: false },
      careerInterruptedWoman: { field: { type: 'text', label: '경력 단절 여성 여부' }, use: false },
      multiculturalFamily: { field: { type: 'text', label: '다문화가정 여부' }, use: false },
      otherItem: { field: { type: 'text', label: '기타항목' }, use: false },
    },
    sort: 0,
  },         
  {
    id: 'graduateSchool',
    title: '대학원',
    collapse: false,
    selected: false,
    items: {
      overseas: { field: { type: 'text', label: '해외여부' }, use: false },
      country: { field: { type: 'text', label: '국가(해외 선택시)' }, use: false },
      schoolName: { field: { type: 'text', label: '학교명' }, use: false },
      graduateType: { field: { type: 'text', label: '대학원 구분' }, use: false },
      majorCategory: { field: { type: 'text', label: '전공계열' }, use: false },
      major: { field: { type: 'text', label: '주전공' }, use: false },
      schoolLocation: { field: { type: 'text', label: '학교소재지' }, use: false },
      earnedCredits: { field: { type: 'text', label: '이수학점' }, use: false },
      totalCredits: { field: { type: 'text', label: '기준학점' }, use: false },
      grade: { field: { type: 'text', label: '학점' }, use: false },
      gradeDetail: { field: { type: 'text', label: '학점 상세' }, use: false },
      advisor: { field: { type: 'text', label: '지도교수' }, use: false },
      labName: { field: { type: 'text', label: 'Lab명' }, use: false },
      transcript: { field: { type: 'text', label: '성적증명서' }, use: false },
      enrollmentCertificate: { field: { type: 'text', label: '재학증명서' }, use: false },
      graduationStatus: { field: { type: 'text', label: '졸업 구분' }, use: false },
      enrollmentPeriod: { field: { type: 'text', label: '재학기간' }, use: false },
      dayOrNight: { field: { type: 'text', label: '주·야간' }, use: false },
      mainOrBranch: { field: { type: 'text', label: '본·분교' }, use: false },
      extraInfo: { field: { type: 'text', label: '추가정보' }, use: false },
    },
    sort: 0,
  },          
  {
    id: 'university',
    title: '대학교',
    collapse: false,
    selected: false,
    items: {
      overseas: { field: { type: 'text', label: '해외여부' }, use: false },
      country: { field: { type: 'text', label: '국가(해외 선택시)' }, use: false },
      schoolName: { field: { type: 'text', label: '학교명' }, use: false },
      major: { field: { type: 'text', label: '주전공' }, use: false },
      majorCategory: { field: { type: 'text', label: '전공계열' }, use: false },
      minorType: { field: { type: 'text', label: '부전공 구분' }, use: false },
      minorOrDoubleMajor: { field: { type: 'text', label: '부전공·복수전공' }, use: false },
      schoolLocation: { field: { type: 'text', label: '학교소재지' }, use: false },
      earnedCredits: { field: { type: 'text', label: '이수 학점' }, use: false },
      totalCredits: { field: { type: 'text', label: '기준 학점' }, use: false },
      grade: { field: { type: 'text', label: '학점' }, use: false },
      gradeDetail: { field: { type: 'text', label: '학점 상세' }, use: false },
      transcript: { field: { type: 'text', label: '성적증명서' }, use: false },
      enrollmentCertificate: { field: { type: 'text', label: '재학증명서' }, use: false },
      graduationStatus: { field: { type: 'text', label: '졸업 구분' }, use: false },
      enrollmentPeriod: { field: { type: 'text', label: '재학기간' }, use: false },
      dayOrNight: { field: { type: 'text', label: '주·야간' }, use: false },
      transferStatus: { field: { type: 'text', label: '편입여부' }, use: false },
      mainOrBranch: { field: { type: 'text', label: '본·분교' }, use: false },
      extraInfo: { field: { type: 'text', label: '추가정보' }, use: false },
    },
    sort: 0,
  },       
  {
    id: 'college',
    title: '전문대학',
    collapse: false,
    selected: false,
    items: {
      overseas: { field: { type: 'text', label: '해외여부' }, use: false },
      country: { field: { type: 'text', label: '국가(해외 선택시)' }, use: false },
      schoolName: { field: { type: 'text', label: '학교명' }, use: false },
      major: { field: { type: 'text', label: '주전공' }, use: false },
      majorCategory: { field: { type: 'text', label: '전공계열' }, use: false },
      minorType: { field: { type: 'text', label: '부전공 구분' }, use: false },
      minorOrDoubleMajor: { field: { type: 'text', label: '부전공·복수전공' }, use: false },
      schoolLocation: { field: { type: 'text', label: '학교소재지' }, use: false },
      earnedCredits: { field: { type: 'text', label: '이수 학점' }, use: false },
      totalCredits: { field: { type: 'text', label: '기준 학점' }, use: false },
      grade: { field: { type: 'text', label: '학점' }, use: false },
      gradeDetail: { field: { type: 'text', label: '학점 상세' }, use: false },
      transcript: { field: { type: 'text', label: '성적증명서' }, use: false },
      enrollmentCertificate: { field: { type: 'text', label: '재학증명서' }, use: false },
      graduationStatus: { field: { type: 'text', label: '졸업 구분' }, use: false },
      enrollmentPeriod: { field: { type: 'text', label: '재학기간' }, use: false },
      dayOrNight: { field: { type: 'text', label: '주·야간' }, use: false },
      transferStatus: { field: { type: 'text', label: '편입여부' }, use: false },
      mainOrBranch: { field: { type: 'text', label: '본·분교' }, use: false },
      extraInfo: { field: { type: 'text', label: '추가정보' }, use: false },
    },
    sort: 0,
  },          
  {
    id: 'highSchool',
    title: '고등학교',
    collapse: false,
    selected: false,
    items: {
      overseas: { field: { type: 'text', label: '해외여부' }, use: false },
      country: { field: { type: 'text', label: '국가(해외 선택시)' }, use: false },
      schoolName: { field: { type: 'text', label: '학교명' }, use: false },
      major: { field: { type: 'text', label: '주전공' }, use: false },
      majorCategory: { field: { type: 'text', label: '전공계열' }, use: false },
      minorType: { field: { type: 'text', label: '부전공 구분' }, use: false },
      minorOrDoubleMajor: { field: { type: 'text', label: '부전공·복수전공' }, use: false },
      schoolLocation: { field: { type: 'text', label: '학교소재지' }, use: false },
      earnedCredits: { field: { type: 'text', label: '이수 학점' }, use: false },
      totalCredits: { field: { type: 'text', label: '기준 학점' }, use: false },
      grade: { field: { type: 'text', label: '학점' }, use: false },
      gradeDetail: { field: { type: 'text', label: '학점 상세' }, use: false },
      transcript: { field: { type: 'text', label: '성적증명서' }, use: false },
      enrollmentCertificate: { field: { type: 'text', label: '재학증명서' }, use: false },
      graduationStatus: { field: { type: 'text', label: '졸업 구분' }, use: false },
      enrollmentPeriod: { field: { type: 'text', label: '재학기간' }, use: false },
      dayOrNight: { field: { type: 'text', label: '주·야간' }, use: false },
      transferStatus: { field: { type: 'text', label: '편입여부' }, use: false },
      mainOrBranch: { field: { type: 'text', label: '본·분교' }, use: false },
      extraInfo: { field: { type: 'text', label: '추가정보' }, use: false },
    },
    sort: 0,
  },             
  {
    id: 'languageTests',
    title: '외국어시험',
    collapse: false,
    selected: false,
    items: {
      languageType: { field: { type: 'text', label: '언어구분' }, use: false },
      testName: { field: { type: 'text', label: '시험명' }, use: false },
      score: { field: { type: 'text', label: '점수' }, use: false },
      grade: { field: { type: 'text', label: '등급' }, use: false },
      acquiredAt: { field: { type: 'text', label: '취득시기' }, use: false },
      registrationNumber: { field: { type: 'text', label: '등록번호' }, use: false },
      certificate: { field: { type: 'text', label: '증빙서류' }, use: false },
    },
    sort: 0,
  },            
  {
    id: 'certifications',
    title: '자격증',
    collapse: false,
    selected: false,
    items: {
      certificateName: { field: { type: 'text', label: '자격증명' }, use: false },
      issuingAgency: { field: { type: 'text', label: '발행처' }, use: false },
      passStatus: { field: { type: 'text', label: '합격구분' }, use: false },
      acquiredAt: { field: { type: 'text', label: '취득시기' }, use: false },
      registrationNumber: { field: { type: 'text', label: '등록번호' }, use: false },
      certificate: { field: { type: 'text', label: '증빙서류' }, use: false },
    },
    sort: 0,
  },           
  {
    id: 'languageSkills',
    title: '외국어활용능력',
    collapse: false,
    selected: false,
    items:  {
      languageName: { field: { type: 'text', label: '언어명' }, use: false },
      speakingLevel: { field: { type: 'text', label: '회화수준' }, use: false },
      writingLevel: { field: { type: 'text', label: '작문수준' }, use: false },
      readingLevel: { field: { type: 'text', label: '독해수준' }, use: false },
    },
    sort: 0,
  },         
  {
    id: 'education',
    title: '교육사항',
    collapse: false,
    selected: false,
    items: {
      educationType: { field: { type: 'text', label: '교육구분' }, use: false },
      courseName: { field: { type: 'text', label: '교육과정' }, use: false },
      institution: { field: { type: 'text', label: '교육기관' }, use: false },
      hours: { field: { type: 'text', label: '교육시간' }, use: false },
      duration: { field: { type: 'text', label: '교육기간' }, use: false },
      content: { field: { type: 'text', label: '교육내용' }, use: false },
      certificateFile: { field: { type: 'text', label: '증빙서류' }, use: false },
    },
    sort: 0,
  },        
  {
    id: 'itSkills',
    title: 'IT활용 능력',
    collapse: false,
    selected: false,
    items: {
      techName: { field: { type: 'text', label: 'IT기술명' }, use: false },
      techType: { field: { type: 'text', label: 'IT기술유형' }, use: false },
      proficiency: { field: { type: 'text', label: '활용수준' }, use: false },
      monthsUsed: { field: { type: 'text', label: '사용개월수' }, use: false },
      description: { field: { type: 'text', label: '상세설명' }, use: false },
    },
    sort: 0,
  },           
   {
    id: 'experiences',
    title: '경험사항',
    collapse: false,
    selected: false,
    items: {
      organizationName: { field: { type: 'text', label: '경험단체명' }, use: false },
      experienceType: { field: { type: 'text', label: '경험구분' }, use: false },
      period: { field: { type: 'text', label: '경험기간' }, use: false },
      responsibility: { field: { type: 'text', label: '담당업무' }, use: false },
      certificateFile: { field: { type: 'text', label: '증빙서류' }, use: false },
    },
    sort: 0,
  },      
  {
    id: 'career',
    title: '경력사항',
    collapse: false,
    selected: false,
    items: {
      companyName: { field: { type: 'text', label: '회사명' }, use: false },
      industry: { field: { type: 'text', label: '업종' }, use: false },
      employmentType: { field: { type: 'text', label: '고용형태' }, use: false },
      position: { field: { type: 'text', label: '직급' }, use: false },
      yearsOfService: { field: { type: 'text', label: '연차' }, use: false },
      isCurrent: { field: { type: 'text', label: '재직여부' }, use: false },
      workPeriod: { field: { type: 'text', label: '근무기간' }, use: false },
      reasonForLeaving: { field: { type: 'text', label: '퇴직사유' }, use: false },
      workLocation: { field: { type: 'text', label: '근무지역' }, use: false },
      department: { field: { type: 'text', label: '근무부서' }, use: false },
      salary: { field: { type: 'text', label: '연봉' }, use: false },
      duties: { field: { type: 'text', label: '담당업무' }, use: false },
      projectHistory: { field: { type: 'text', label: '프로젝트 이력' }, use: false },
    },
    sort: 0,
  },              
  {
    id: 'additionalInfo',
    title: '추가정보 (파일/링크)',
    collapse: false,
    selected: false,
    items: {
      resume: { field: { type: 'text', label: '이력서' }, use: false },
      careerDescription: { field: { type: 'text', label: '경력기술서' }, use: false },
      certificate: { field: { type: 'text', label: '자격증' }, use: false },
      officialDocument: { field: { type: 'text', label: '증명서' }, use: false },
      portfolio: { field: { type: 'text', label: '포트폴리오' }, use: false },
      plan: { field: { type: 'text', label: '기획서' }, use: false },
      etcFile: { field: { type: 'text', label: '기타' }, use: false },
    },
    sort: 0,
  },
  {
    id: 'careerDescriptions',
    title: '경력기술서',
    collapse: false,
    selected: false,
    items: {
      shortAnswer: { field: { type: 'text', label: '문항 작성, 단문형(~300자)' }, use: false },
      longAnswer: { field: { type: 'text', label: '문항 작성, 장문형(~3000자)' }, use: false },
    },
    sort: 0,
  },       
  {
    id: 'selfIntroduction',
    title: '자기소개서',
    collapse: false,
    selected: false,
    items: {
      shortAnswer: { field: { type: 'text', label: '문항 작성, 단문형(~300자)' }, use: false },
      longAnswer: { field: { type: 'text', label: '문항 작성, 장문형(~3000자)' }, use: false },
    },
    sort: 0,
  },      
]


export const usableFieldsObject: { [key in FormFieldGroupType]: UsableFormFieldGroup } = {
  applicationInfo: {
    id: 'applicationInfo',
    title: '지원정보',
    collapse: false,
    selected: false,
    items: {
      jobPosition: { field: { type: 'text', label: '지원 직무' }, use: false },
      preferredLocation: { field: { type: 'text', label: '희망 근무지' }, use: false },
      applicationSource: { field: { type: 'text', label: '지원 경로' }, use: false },
      desiredSalary: { field: { type: 'text', label: '희망 연봉' }, use: false },
      previousSalary: { field: { type: 'text', label: '직전 연봉' }, use: false },
      availableStartDate: { field: { type: 'text', label: '입사가능일자' }, use: false },
      previousPosition: { field: { type: 'text', label: '직전직급' }, use: false },
      applicationPath: { field: { type: 'text', label: '지원경로' }, use: false },
    },
    sort: 0,
  },          
  personalInfo: {
    id: 'personalInfo',
    title: '인적정보',
    collapse: false,
    selected: false,
    items: {
      photo: { field: { type: 'text', label: '사진' }, use: false },
      name: { field: { type: 'text', label: '이름' }, use: false },
      englishName: { field: { type: 'text', label: '영문 이름' }, use: false },
      phoneNumber: { field: { type: 'text', label: '휴대폰 번호' }, use: false },
      email: { field: { type: 'text', label: '이메일' }, use: false },
      emergencyContact: { field: { type: 'text', label: '긴급 연락처' }, use: false },
      birthDate: { field: { type: 'text', label: '생년월일' }, use: false },
      gender: { field: { type: 'text', label: '성별' }, use: false },
      hobby: { field: { type: 'text', label: '취미' }, use: false },
      specialty: { field: { type: 'text', label: '특기' }, use: false },
      colorVision: { field: { type: 'text', label: '색약여부' }, use: false },
      militaryService: { field: { type: 'text', label: '병역' }, use: false },
      address: { field: { type: 'text', label: '주소' }, use: false },
      snsUrl: { field: { type: 'text', label: 'SNS주소' }, use: false },
      nationality: { field: { type: 'text', label: '국적' }, use: false },
    },
    sort: 0,
  },             
  summaryInfo: {
    id: 'summaryInfo',
    title: '요약정보',
    collapse: false,
    selected: false,
    items: {

    },
    sort: 0,
  },              
  additionalPoints: {
    id: 'additionalPoints',
    title: '가산점',
    collapse: false,
    selected: false,
    items: {
      disability: { field: { type: 'text', label: '장애 여부' }, use: false },
      veteransStatus: { field: { type: 'text', label: '보훈 대상 여부' }, use: false },
      localTalent: { field: { type: 'text', label: '지역 인재' }, use: false },
      formerLocalTalent: { field: { type: 'text', label: '이전 지역 인재' }, use: false },
      singleParent: { field: { type: 'text', label: '한부모 가족 여부' }, use: false },
      northKoreanDefector: { field: { type: 'text', label: '북한 이탈 주민 여부' }, use: false },
      basicLivingRecipient: { field: { type: 'text', label: '기초생활 수급 여부' }, use: false },
      lowIncome: { field: { type: 'text', label: '차상위계층여부' }, use: false },
      youth: { field: { type: 'text', label: '청년 여부' }, use: false },
      careerInterruptedWoman: { field: { type: 'text', label: '경력 단절 여성 여부' }, use: false },
      multiculturalFamily: { field: { type: 'text', label: '다문화가정 여부' }, use: false },
      otherItem: { field: { type: 'text', label: '기타항목' }, use: false },
    },
    sort: 0,
  },         
  graduateSchool: {
    id: 'graduateSchool',
    title: '대학원',
    collapse: false,
    selected: false,
    items: {
      overseas: { field: { type: 'text', label: '해외여부' }, use: false },
      country: { field: { type: 'text', label: '국가(해외 선택시)' }, use: false },
      schoolName: { field: { type: 'text', label: '학교명' }, use: false },
      graduateType: { field: { type: 'text', label: '대학원 구분' }, use: false },
      majorCategory: { field: { type: 'text', label: '전공계열' }, use: false },
      major: { field: { type: 'text', label: '주전공' }, use: false },
      schoolLocation: { field: { type: 'text', label: '학교소재지' }, use: false },
      earnedCredits: { field: { type: 'text', label: '이수학점' }, use: false },
      totalCredits: { field: { type: 'text', label: '기준학점' }, use: false },
      grade: { field: { type: 'text', label: '학점' }, use: false },
      gradeDetail: { field: { type: 'text', label: '학점 상세' }, use: false },
      advisor: { field: { type: 'text', label: '지도교수' }, use: false },
      labName: { field: { type: 'text', label: 'Lab명' }, use: false },
      transcript: { field: { type: 'text', label: '성적증명서' }, use: false },
      enrollmentCertificate: { field: { type: 'text', label: '재학증명서' }, use: false },
      graduationStatus: { field: { type: 'text', label: '졸업 구분' }, use: false },
      enrollmentPeriod: { field: { type: 'text', label: '재학기간' }, use: false },
      dayOrNight: { field: { type: 'text', label: '주·야간' }, use: false },
      mainOrBranch: { field: { type: 'text', label: '본·분교' }, use: false },
      extraInfo: { field: { type: 'text', label: '추가정보' }, use: false },
    },
    sort: 0,
  },           
  university: {
    id: 'university',
    title: '대학교',
    collapse: false,
    selected: false,
    items: {
      overseas: { field: { type: 'text', label: '해외여부' }, use: false },
      country: { field: { type: 'text', label: '국가(해외 선택시)' }, use: false },
      schoolName: { field: { type: 'text', label: '학교명' }, use: false },
      major: { field: { type: 'text', label: '주전공' }, use: false },
      majorCategory: { field: { type: 'text', label: '전공계열' }, use: false },
      minorType: { field: { type: 'text', label: '부전공 구분' }, use: false },
      minorOrDoubleMajor: { field: { type: 'text', label: '부전공·복수전공' }, use: false },
      schoolLocation: { field: { type: 'text', label: '학교소재지' }, use: false },
      earnedCredits: { field: { type: 'text', label: '이수 학점' }, use: false },
      totalCredits: { field: { type: 'text', label: '기준 학점' }, use: false },
      grade: { field: { type: 'text', label: '학점' }, use: false },
      gradeDetail: { field: { type: 'text', label: '학점 상세' }, use: false },
      transcript: { field: { type: 'text', label: '성적증명서' }, use: false },
      enrollmentCertificate: { field: { type: 'text', label: '재학증명서' }, use: false },
      graduationStatus: { field: { type: 'text', label: '졸업 구분' }, use: false },
      enrollmentPeriod: { field: { type: 'text', label: '재학기간' }, use: false },
      dayOrNight: { field: { type: 'text', label: '주·야간' }, use: false },
      transferStatus: { field: { type: 'text', label: '편입여부' }, use: false },
      mainOrBranch: { field: { type: 'text', label: '본·분교' }, use: false },
      extraInfo: { field: { type: 'text', label: '추가정보' }, use: false },
    },
    sort: 0,
  },               
  college: {
    id: 'college',
    title: '전문대학',
    collapse: false,
    selected: false,
    items: {
      overseas: { field: { type: 'text', label: '해외여부' }, use: false },
      country: { field: { type: 'text', label: '국가(해외 선택시)' }, use: false },
      schoolName: { field: { type: 'text', label: '학교명' }, use: false },
      major: { field: { type: 'text', label: '주전공' }, use: false },
      majorCategory: { field: { type: 'text', label: '전공계열' }, use: false },
      minorType: { field: { type: 'text', label: '부전공 구분' }, use: false },
      minorOrDoubleMajor: { field: { type: 'text', label: '부전공·복수전공' }, use: false },
      schoolLocation: { field: { type: 'text', label: '학교소재지' }, use: false },
      earnedCredits: { field: { type: 'text', label: '이수 학점' }, use: false },
      totalCredits: { field: { type: 'text', label: '기준 학점' }, use: false },
      grade: { field: { type: 'text', label: '학점' }, use: false },
      gradeDetail: { field: { type: 'text', label: '학점 상세' }, use: false },
      transcript: { field: { type: 'text', label: '성적증명서' }, use: false },
      enrollmentCertificate: { field: { type: 'text', label: '재학증명서' }, use: false },
      graduationStatus: { field: { type: 'text', label: '졸업 구분' }, use: false },
      enrollmentPeriod: { field: { type: 'text', label: '재학기간' }, use: false },
      dayOrNight: { field: { type: 'text', label: '주·야간' }, use: false },
      transferStatus: { field: { type: 'text', label: '편입여부' }, use: false },
      mainOrBranch: { field: { type: 'text', label: '본·분교' }, use: false },
      extraInfo: { field: { type: 'text', label: '추가정보' }, use: false },
    },
    sort: 0,
  },                  
  highSchool: {
    id: 'highSchool',
    title: '고등학교',
    collapse: false,
    selected: false,
    items: {
      overseas: { field: { type: 'text', label: '해외여부' }, use: false },
      country: { field: { type: 'text', label: '국가(해외 선택시)' }, use: false },
      schoolName: { field: { type: 'text', label: '학교명' }, use: false },
      major: { field: { type: 'text', label: '주전공' }, use: false },
      majorCategory: { field: { type: 'text', label: '전공계열' }, use: false },
      minorType: { field: { type: 'text', label: '부전공 구분' }, use: false },
      minorOrDoubleMajor: { field: { type: 'text', label: '부전공·복수전공' }, use: false },
      schoolLocation: { field: { type: 'text', label: '학교소재지' }, use: false },
      earnedCredits: { field: { type: 'text', label: '이수 학점' }, use: false },
      totalCredits: { field: { type: 'text', label: '기준 학점' }, use: false },
      grade: { field: { type: 'text', label: '학점' }, use: false },
      gradeDetail: { field: { type: 'text', label: '학점 상세' }, use: false },
      transcript: { field: { type: 'text', label: '성적증명서' }, use: false },
      enrollmentCertificate: { field: { type: 'text', label: '재학증명서' }, use: false },
      graduationStatus: { field: { type: 'text', label: '졸업 구분' }, use: false },
      enrollmentPeriod: { field: { type: 'text', label: '재학기간' }, use: false },
      dayOrNight: { field: { type: 'text', label: '주·야간' }, use: false },
      transferStatus: { field: { type: 'text', label: '편입여부' }, use: false },
      mainOrBranch: { field: { type: 'text', label: '본·분교' }, use: false },
      extraInfo: { field: { type: 'text', label: '추가정보' }, use: false },
    },
    sort: 0,
  },               
  languageTests: {
    id: 'languageTests',
    title: '외국어시험',
    collapse: false,
    selected: false,
    items: {
      languageType: { field: { type: 'text', label: '언어구분' }, use: false },
      testName: { field: { type: 'text', label: '시험명' }, use: false },
      score: { field: { type: 'text', label: '점수' }, use: false },
      grade: { field: { type: 'text', label: '등급' }, use: false },
      acquiredAt: { field: { type: 'text', label: '취득시기' }, use: false },
      registrationNumber: { field: { type: 'text', label: '등록번호' }, use: false },
      certificate: { field: { type: 'text', label: '증빙서류' }, use: false },
    },
    sort: 0,
  },            
  certifications: {
    id: 'certifications',
    title: '자격증',
    collapse: false,
    selected: false,
    items: {
      certificateName: { field: { type: 'text', label: '자격증명' }, use: false },
      issuingAgency: { field: { type: 'text', label: '발행처' }, use: false },
      passStatus: { field: { type: 'text', label: '합격구분' }, use: false },
      acquiredAt: { field: { type: 'text', label: '취득시기' }, use: false },
      registrationNumber: { field: { type: 'text', label: '등록번호' }, use: false },
      certificate: { field: { type: 'text', label: '증빙서류' }, use: false },
    },
    sort: 0,
  },           
  languageSkills: {
    id: 'languageSkills',
    title: '외국어활용능력',
    collapse: false,
    selected: false,
    items:  {
      languageName: { field: { type: 'text', label: '언어명' }, use: false },
      speakingLevel: { field: { type: 'text', label: '회화수준' }, use: false },
      writingLevel: { field: { type: 'text', label: '작문수준' }, use: false },
      readingLevel: { field: { type: 'text', label: '독해수준' }, use: false },
    },
    sort: 0,
  },           
  education: {
    id: 'education',
    title: '교육사항',
    collapse: false,
    selected: false,
    items: {
      educationType: { field: { type: 'text', label: '교육구분' }, use: false },
      courseName: { field: { type: 'text', label: '교육과정' }, use: false },
      institution: { field: { type: 'text', label: '교육기관' }, use: false },
      hours: { field: { type: 'text', label: '교육시간' }, use: false },
      duration: { field: { type: 'text', label: '교육기간' }, use: false },
      content: { field: { type: 'text', label: '교육내용' }, use: false },
      certificateFile: { field: { type: 'text', label: '증빙서류' }, use: false },
    },
    sort: 0,
  },                
  itSkills: {
    id: 'itSkills',
    title: 'IT활용 능력',
    collapse: false,
    selected: false,
    items: {
      techName: { field: { type: 'text', label: 'IT기술명' }, use: false },
      techType: { field: { type: 'text', label: 'IT기술유형' }, use: false },
      proficiency: { field: { type: 'text', label: '활용수준' }, use: false },
      monthsUsed: { field: { type: 'text', label: '사용개월수' }, use: false },
      description: { field: { type: 'text', label: '상세설명' }, use: false },
    },
    sort: 0,
  },                 
  experiences: {
    id: 'experiences',
    title: '경험사항',
    collapse: false,
    selected: false,
    items: {
      organizationName: { field: { type: 'text', label: '경험단체명' }, use: false },
      experienceType: { field: { type: 'text', label: '경험구분' }, use: false },
      period: { field: { type: 'text', label: '경험기간' }, use: false },
      responsibility: { field: { type: 'text', label: '담당업무' }, use: false },
      certificateFile: { field: { type: 'text', label: '증빙서류' }, use: false },
    },
    sort: 0,
  },             
  career: {
    id: 'career',
    title: '경력사항',
    collapse: false,
    selected: false,
    items: {
      companyName: { field: { type: 'text', label: '회사명' }, use: false },
      industry: { field: { type: 'text', label: '업종' }, use: false },
      employmentType: { field: { type: 'text', label: '고용형태' }, use: false },
      position: { field: { type: 'text', label: '직급' }, use: false },
      yearsOfService: { field: { type: 'text', label: '연차' }, use: false },
      isCurrent: { field: { type: 'text', label: '재직여부' }, use: false },
      workPeriod: { field: { type: 'text', label: '근무기간' }, use: false },
      reasonForLeaving: { field: { type: 'text', label: '퇴직사유' }, use: false },
      workLocation: { field: { type: 'text', label: '근무지역' }, use: false },
      department: { field: { type: 'text', label: '근무부서' }, use: false },
      salary: { field: { type: 'text', label: '연봉' }, use: false },
      duties: { field: { type: 'text', label: '담당업무' }, use: false },
      projectHistory: { field: { type: 'text', label: '프로젝트 이력' }, use: false },
    },
    sort: 0,
  },                   
  additionalInfo: {
    id: 'additionalInfo',
    title: '추가정보 (파일/링크)',
    collapse: false,
    selected: false,
    items: {
      resume: { field: { type: 'text', label: '이력서' }, use: false },
      careerDescription: { field: { type: 'text', label: '경력기술서' }, use: false },
      certificate: { field: { type: 'text', label: '자격증' }, use: false },
      officialDocument: { field: { type: 'text', label: '증명서' }, use: false },
      portfolio: { field: { type: 'text', label: '포트폴리오' }, use: false },
      plan: { field: { type: 'text', label: '기획서' }, use: false },
      etcFile: { field: { type: 'text', label: '기타' }, use: false },
    },
    sort: 0,
  },
  careerDescriptions: {
    id: 'careerDescriptions',
    title: '경력기술서',
    collapse: false,
    selected: false,
    items: {
      shortAnswer: { field: { type: 'text', label: '문항 작성, 단문형(~300자)' }, use: false },
      longAnswer: { field: { type: 'text', label: '문항 작성, 장문형(~3000자)' }, use: false },
    },
    sort: 0,
  },       
  selfIntroduction: {
    id: 'selfIntroduction',
    title: '자기소개서',
    collapse: false,
    selected: false,
    items: {
      shortAnswer: { field: { type: 'text', label: '문항 작성, 단문형(~300자)' }, use: false },
      longAnswer: { field: { type: 'text', label: '문항 작성, 장문형(~3000자)' }, use: false },
    },
    sort: 0,
  },      
}